### PR TITLE
Fix space in script path and Fix new file explorer instance error

### PR DESCRIPTION
**Pull request by Mis1eader-dev**
Currently if the directory path to `Register.cmd` or `Uninstall.cmd` contains spaces, a UAC prompt will come up, after accepting the prompt it closes and does nothing.

This patch fixes two bugs:
1. Space in full path to scripts.
2. If `Register.cmd` is ran and instead of closing the file explorer window if you open a new instance of file explorer, it causes a crash, as shown in the next picture.

image

### CODE REVIEW

**Comment by Maplespe** [comment]
You mentioned that you fixed 
> "If Register.cmd is ran and instead of closing the file explorer window if you open a new instance of file explorer, it causes a crash, as shown in the next picture."

But there doesn't seem to be a relevant source code change in the commit?
Also there is an encoding error in the `"Uninstall.cmd"` file.

**Comment by Maplespe** [comment]
You mentioned that you fixed "If Register.cmd is ran and instead of closing the file explorer window if you open a new instance of file explorer, it causes a crash, as shown in the next picture."
But there doesn't seem to be a relevant source code change in the commit?
Also there is an encoding error in the "Uninstall.cmd" file.

**Comment by Mis1eader-dev** [comment]
> You mentioned that you fixed 
> > "If Register.cmd is ran and instead of closing the file explorer window if you open a new instance of file explorer, it causes a crash, as shown in the next picture."
> 
> But there doesn't seem to be a relevant source code change in the commit?
> Also there is an encoding error in the `"Uninstall.cmd"` file.

The taskkill at the end of `Register.cmd` is responsible for not allowing the user to create a new instance.

**Comment by Mis1eader-dev** [comment]
I will fix the encoding in a moment. VSCode messed it up.

**Comment by Maplespe** [comment]
Well, the coding is still wrong, but I will fix it, thank you.

**Pull request merged**
